#!/bin/bash
# push_to_docker_hub.sh - Script for pushing Docker images to Docker Hub

# Text styling
BOLD='\033[1m'
NORMAL='\033[0m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'

REPOSITORY="fioresxcat/table2html-annotation"

echo -e "${BOLD}${GREEN}Pushing Table Annotation Tool images to Docker Hub${NORMAL}"
echo

# Check if docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed or not in PATH${NORMAL}"
    exit 1
fi

# Check if user is logged in to Docker Hub
echo -e "${BLUE}Checking Docker Hub login status...${NORMAL}"
if ! docker info | grep -q "Username"; then
    echo -e "${YELLOW}You are not logged in to Docker Hub. Please login:${NORMAL}"
    docker login
    
    # Verify login was successful
    if [ $? -ne 0 ]; then
        echo -e "${RED}Docker Hub login failed. Aborting.${NORMAL}"
        exit 1
    fi
fi

# Build the images first
echo -e "${BLUE}Building Docker images...${NORMAL}"
docker-compose build

# Get the actual image names generated by docker-compose
PROJECT_NAME=$(basename $(pwd) | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]//g')
if [ -z "$PROJECT_NAME" ]; then
    PROJECT_NAME="table-annotation"
fi

# Tag the images
echo -e "${BLUE}Tagging images with Docker Hub repository name...${NORMAL}"
docker tag ${PROJECT_NAME}_frontend ${REPOSITORY}:frontend
docker tag ${PROJECT_NAME}_backend ${REPOSITORY}:backend

# Push the images
echo -e "${BLUE}Pushing frontend image to Docker Hub...${NORMAL}"
docker push ${REPOSITORY}:frontend

echo -e "${BLUE}Pushing backend image to Docker Hub...${NORMAL}"
docker push ${REPOSITORY}:backend

echo
echo -e "${GREEN}${BOLD}Success!${NORMAL} Images have been pushed to Docker Hub repository: ${BOLD}${REPOSITORY}${NORMAL}"
echo
echo -e "Team members can now pull these images using:"
echo -e "${YELLOW}docker pull ${REPOSITORY}:frontend${NORMAL}"
echo -e "${YELLOW}docker pull ${REPOSITORY}:backend${NORMAL}"
echo
echo -e "They should also use ${BOLD}./run.sh --no-build${NORMAL} to use the pre-built images." 